# This file contains per-environment settings for AnyCable.
#
# Since AnyCable config is based on anyway_config (https://github.com/palkan/anyway_config), all AnyCable settings
# can be set or overridden through the corresponding environment variables.
# E.g., `rpc_host` is overridden by ANYCABLE_RPC_HOST, `debug` by ANYCABLE_DEBUG etc.
#
# Note that AnyCable recognizes REDIS_URL env variable for Redis pub/sub adapter. If you want to
# use another Redis instance for AnyCable, provide ANYCABLE_REDIS_URL variable.
#
# Read more about AnyCable configuration here: https://docs.anycable.io/ruby/configuration
#
default: &default # Turn on/off access logs ("Started..." and "Finished...")
  access_logs_disabled: false
  # Whether to enable gRPC level logging or not
  log_grpc: true
  # Use HTTP broadcaster
  broadcast_adapter: redis
  redis_channel: __anycable__

  # http_broadcast_url: "http://localhost:8090/_broadcast"
  # Must be the same as in your AnyCable server config
  secret: <%= ENV.fetch("ANYCABLE_SECRET") { 'anycable_key' } %>
  websocket_url: <%= ENV.fetch("CABLE_URL", "ws://localhost:8080/cable") %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  websocket_url: <%= ENV.fetch("CABLE_URL") %>
  secret: <%= ENV.fetch("ANYCABLE_SECRET") %>
