default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV['DB_PORT'] %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_PREFIX", "pro_rails") %>_development
  queue:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_PREFIX", "pro_rails") %>_queue_development
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_PREFIX", "pro_rails") %>_test

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_PREFIX", "pro_rails") %>_production
  cache:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_PREFIX", "pro_rails") %>_cache_production
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_PREFIX", "pro_rails") %>_queue_production
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_PREFIX", "pro_rails") %>_cable_production
    migrations_paths: db/cable_migrate
